# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: rest_api-postgres
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: 2222

  adminer:
    image: adminer
    container_name: rest_api-adminer
    restart: unless-stopped
    ports:
      - 8099:8080