bind_addr = ":8080"
log_level = "debug"

[store]
#database_url = "host=localhost:54321 dbname=rest_api sslmode=disable"
database_url = "postgresql://postgres:2222@localhost:54321/rest_api?sslmode=disable"
